import { NodeType } from '@/types/workflow';
import type { NodeTemplate } from '@/types/workflow';

export const NODE_TEMPLATES: NodeTemplate[] = [
  {
    type: NodeType.START,
    label: '开始',
    icon: 'Play',
    color: '#22c55e',
    category: 'basic',
    defaultData: { label: '开始', outputs: [] },
  },
  {
    type: NodeType.LLM,
    label: 'LLM 推理',
    icon: 'Bot',
    color: '#8b5cf6',
    category: 'basic',
    defaultData: {
      label: 'LLM 推理',
      systemPrompt: '你是一个有帮助的助手。',
      userPromptTemplate: '{{user_input}}',
      model: 'qwen3-32b',
      temperature: 0.7,
      topP: 0.9,
      maxTokens: 2048,
      enableTools: false,
      allowedTools: [],
      outputFormat: 'text',
      outputVariable: 'result',
    },
  },
  {
    type: NodeType.TOOL,
    label: '工具',
    icon: 'Wrench',
    color: '#f59e0b',
    category: 'basic',
    defaultData: {
      label: '工具',
      toolName: '',
      toolParams: {},
      paramMapping: {},
      outputVariable: 'tool_result',
    },
  },
  {
    type: NodeType.CONDITION,
    label: '条件分支',
    icon: 'GitBranch',
    color: '#06b6d4',
    category: 'logic',
    defaultData: {
      label: '条件分支',
      branches: [
        { id: 'b1', label: '是', condition: 'true', targetHandle: 'yes' },
        { id: 'b2', label: '否', condition: 'false', targetHandle: 'no' },
      ],
      defaultBranch: 'no',
    },
  },
  {
    type: NodeType.LOOP,
    label: 'ReAct 循环',
    icon: 'RefreshCw',
    color: '#ec4899',
    category: 'logic',
    defaultData: {
      label: 'ReAct 循环',
      maxIterations: 10,
      exitCondition: '',
      contextVariable: 'loop_context',
      appendMode: 'append',
    },
  },
  {
    type: NodeType.HUMAN,
    label: '人工审批',
    icon: 'UserCheck',
    color: '#14b8a6',
    category: 'advanced',
    defaultData: {
      label: '人工审批',
      interactionType: 'approve',
      displayTemplate: '请确认是否继续？',
      timeoutSeconds: 0,
      timeoutAction: 'reject',
      outputVariable: 'approval',
    },
  },
  {
    type: NodeType.VARIABLE,
    label: '变量赋值',
    icon: 'Variable',
    color: '#64748b',
    category: 'logic',
    defaultData: {
      label: '变量赋值',
      expression: '',
      outputVariable: '',
    },
  },
  {
    type: NodeType.SKILL,
    label: 'Skill 技能',
    icon: 'BrainCircuit',
    color: '#a855f7',
    category: 'skill',
    defaultData: {
      label: 'Skill 技能',
      skillId: '',
      skillName: '',
      sourceType: 'user',
      contextMode: 'inline',
      argsTemplate: '{{input}}',
      modelOverride: '',
      allowedTools: [],
      whenToUse: '',
      migrationStatus: '',
      outputVariable: 'skill_result',
    },
  },
  {
    type: NodeType.END,
    label: '结束',
    icon: 'Square',
    color: '#ef4444',
    category: 'basic',
    defaultData: { label: '结束', outputs: [] },
  },
];

export const NODE_CATEGORIES = [
  { key: 'basic', label: '基础节点' },
  { key: 'logic', label: '逻辑节点' },
  { key: 'skill', label: 'Skill 技能' },
  { key: 'advanced', label: '高级节点' },
] as const;
